name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Render LICENSE
        run: npm run render:license

      - name: Render README
        run: npm run render:readme

      - name: Run tests
        run: npm test

      - name: Lint
        run: npm run lint

      - name: Generate Quickstart narrative
        run: npm run narrate

      - name: Build typed graph
        run: npm run graph
